diff /IMSB/ra/mewing/V2_1_3/xquest/bin/annotatexml.pl /IMSB/ra/mewing/xquestClusterVersion/bin/annotatexml.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/checkmodules.pl /IMSB/ra/mewing/xquestClusterVersion/bin/checkmodules.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/compare_peaks3.pl /IMSB/ra/mewing/xquestClusterVersion/bin/compare_peaks3.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/indexspecfiles.pl /IMSB/ra/mewing/xquestClusterVersion/bin/indexspecfiles.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/mergeandcopy.pl /IMSB/ra/mewing/xquestClusterVersion/bin/mergeandcopy.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/mergexml.pl /IMSB/ra/mewing/xquestClusterVersion/bin/mergexml.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/pQuest.pl /IMSB/ra/mewing/xquestClusterVersion/bin/pQuest.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/pseudoSH.pl /IMSB/ra/mewing/xquestClusterVersion/bin/pseudoSH.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/runXquest.pl /IMSB/ra/mewing/xquestClusterVersion/bin/runXquest.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xdecoy.pl /IMSB/ra/mewing/xquestClusterVersion/bin/xdecoy.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xmm.pl /IMSB/ra/mewing/xquestClusterVersion/bin/xmm.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xprophet.pl /IMSB/ra/mewing/xquestClusterVersion/bin/xprophet.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xprophet_optimizer.pl /IMSB/ra/mewing/xquestClusterVersion/bin/xprophet_optimizer.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xq.progress /IMSB/ra/mewing/xquestClusterVersion/bin/xq.progress
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xq.run /IMSB/ra/mewing/xquestClusterVersion/bin/xq.run
diff /IMSB/ra/mewing/V2_1_3/xquest/bin/xquest.pl /IMSB/ra/mewing/xquestClusterVersion/bin/xquest.pl
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Base64.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Base64.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Combinatorics.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Combinatorics.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Common.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Common.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Consensus.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Consensus.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Environment.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Environment.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Index.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Index.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Ionseries.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Ionseries.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/LinkObj.pm /IMSB/ra/mewing/xquestClusterVersion/modules/LinkObj.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Match.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Match.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Norm.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Norm.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/PARAMS.pm /IMSB/ra/mewing/xquestClusterVersion/modules/PARAMS.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/PepObj.pm /IMSB/ra/mewing/xquestClusterVersion/modules/PepObj.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Read_Params.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Read_Params.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/SimpleAuth.pm /IMSB/ra/mewing/xquestClusterVersion/modules/SimpleAuth.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/specplot.pm /IMSB/ra/mewing/xquestClusterVersion/modules/specplot.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Spectrum.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Spectrum.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Statistics.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Statistics.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/xcorr.pm /IMSB/ra/mewing/xquestClusterVersion/modules/xcorr.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Xcorrelation.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Xcorrelation.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/Xquest_Digest.pm /IMSB/ra/mewing/xquestClusterVersion/modules/Xquest_Digest.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/xQuest_mgfscan.pm /IMSB/ra/mewing/xquestClusterVersion/modules/xQuest_mgfscan.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/xQuest_mgfscanTTT.pm /IMSB/ra/mewing/xquestClusterVersion/modules/xQuest_mgfscanTTT.pm
diff /IMSB/ra/mewing/V2_1_3/xquest/modules/xQUEST_mzXMLscan.pm /IMSB/ra/mewing/xquestClusterVersion/modules/xQUEST_mzXMLscan.pm
